services:

  fdpindexproxy:
    image: markw/fdp-index-proxy:0.0.9
    restart: always
    ports:
      - 4000:4567
    environment:
      - FDP_INDEX=https://tools.ostrails.eu/fdp-index/
      - FDP_PROXY_METHOD=https
      - FDP_PROXY_HOST=tools.ostrails.eu
    volumes:
      - $PWD/cache:/server/fdp_index_proxy/cache
    security_opt:
      - apparmor:unconfined
    command: service cron start && ruby /server/fdp_index_proxy/application/controllers/application_controller.rb -o 0.0.0.0
