version: "3"
services:

  fdpindexproxy:
    image: markw/fdp-index-proxy:0.9.0
    restart: always
    ports:
      - 4000:4567
    environment:
      - FDP_INDEX=https://tools.ostrails.eu/fdp-index/
      - FDP_PROXY_METHOD=https
      - FDP_PROXY_HOST=tools.ostrails.eu
      - FDP_CACHE_TTL=600
    volumes:
      - $PWD/cache:/server/cache
    security_opt:
      - apparmor:unconfined
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
