# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in fdp_index_proxy.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "linkeddata", "~> 3.3"

gem "sinatra", "~> 4.0"

gem "json-ld", "~> 3.3"

gem "securerandom", "~> 0.3.1"

gem "swagger-blocks", "~> 3.0"
