# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in fdp_index_proxy.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "linkeddata", "~> 3.3"

gem "sinatra", "~> 4.0"

gem "json-ld", "~> 3.3"

gem "securerandom", "~> 0.3.1"

gem "swagger-blocks", "~> 3.0"

gem "rubocop", "~> 1.67"

gem "require_all", "~> 3.0"

gem "rdf-vocab", "~> 3.3"

gem "webrick", "~> 1.8"

gem "rackup", "~> 2.1"

gem "uri", "~> 0.13.1"

gem "rest-client", "~> 2.1"

gem "erb", "~> 4.0"
